In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('Data.csv')

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [6]:
dataset.Country

0     France
1      Spain
2    Germany
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [7]:
dataset.Age

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [8]:
dataset.Salary

0    72000.0
1    48000.0
2    54000.0
3    61000.0
4        NaN
5    58000.0
6    52000.0
7    79000.0
8    83000.0
9    67000.0
Name: Salary, dtype: float64

In [9]:
dataset.Purchased

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [10]:
dataset['Country']

0     France
1      Spain
2    Germany
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [16]:
dataset['Country'][0:3]

0     France
1      Spain
2    Germany
Name: Country, dtype: object

In [11]:
dataset['Age']

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [12]:
dataset['Salary']

0    72000.0
1    48000.0
2    54000.0
3    61000.0
4        NaN
5    58000.0
6    52000.0
7    79000.0
8    83000.0
9    67000.0
Name: Salary, dtype: float64

In [13]:
dataset['Purchased']

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [22]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [23]:
dataset.tail()

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [25]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [27]:
dataset.iloc[0:2,0:2]

Country   Age
0  France  44.0
1   Spain  27.0

In [31]:
dataset.iloc[0:3,1:3]

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0

In [32]:
# Step - 2
# Input Variables - Features - Independent
# Output Variables - Target Variables - Dependent
# Y=f(X)

# Seperate inputs and outputs
X=dataset.iloc[:,0:-1]

In [33]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [34]:
Y=dataset.iloc[:,-1]

In [35]:
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [36]:
X=X.values

In [37]:
type(X)

numpy.ndarray

In [38]:
Y=Y.values

In [39]:
type(Y)

numpy.ndarray

In [40]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [41]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [42]:
# Step-3 - Cleaning Missing Data
# Imputation 

# a. nan -> col ? cat:num - frequency (cat)
# b. nan -> col ? cat:num - mean (num)

!pip install scikit-learn


In [43]:
from sklearn.impute import SimpleImputer
import numpy as np

si=SimpleImputer(
    missing_values=np.nan,
    strategy='mean'
)
X[:,1:3]=si.fit_transform(X[:,1:3])

In [44]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [45]:
# Step - 4: Encoding

# One-Hot Encoder - Input
# Label Encoder - Output

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(
    transformers=[('encoder',OneHotEncoder(),[0])],
    remainder='passthrough'
)

X=ct.fit_transform(X)

In [46]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [47]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
Y=le.fit_transform(Y)

In [48]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [49]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [50]:
X_train.shape

(8, 5)

In [51]:
X_test.shape

(2, 5)

In [52]:
Y_train.shape

(8,)

In [53]:
Y_test.shape

(2,)

In [54]:
# step-6 - feature scaling
from sklearn.preprocessing import StandardScaler

ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.fit_transform(X_test)


In [55]:
X_train

array([[-0.77459667,  1.29099445, -0.57735027,  1.42153615,  1.52842169],
       [-0.77459667, -0.77459667,  1.73205081, -0.1652949 , -0.44630911],
       [-0.77459667, -0.77459667,  1.73205081, -1.61989003, -1.61319549],
       [ 1.29099445, -0.77459667, -0.57735027, -0.29753082,  0.09225384],
       [ 1.29099445, -0.77459667, -0.57735027,  0.62812062,  0.54105629],
       [-0.77459667,  1.29099445, -0.57735027, -1.22318227, -1.07463254],
       [ 1.29099445, -0.77459667, -0.57735027,  1.15706431,  1.16937973],
       [-0.77459667,  1.29099445, -0.57735027,  0.09917694, -0.19697441]])

In [56]:
X_test

array([[ 1.,  0., -1., -1.,  1.],
       [-1.,  0.,  1.,  1., -1.]])

In [57]:
Y_train

array([0, 0, 1, 1, 0, 0, 1, 1])

In [58]:
Y_test

array([1, 0])